trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- bash: echo "Building..."
- bash: echo "Some artifact content" > $(Build.SourcesDirectory)/out/readme.txt
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)/out'
    artifactName: 'drop'